server:
  port: 8090
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:medium_dev;MODE=MYSQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
custom:
  tempDirPath: c:/temp/medium_test/temp
  genFile:
    dirPath: c:/temp/medium_test